### ISSUE TITLE
[gitpage] : Automatically deploy on github page

### ISSUE THREAD

**Issue by RSS1102** [abcjs-music/abcjs-editor#1]
I think it is possible to deploy this project on the GitHub page through GitHub action, so that others can experience this project faster and more intuitively?

**Comment by paulrosen** [comment]
Thanks! I do have it deployed but I forgot to mention that in the readme. I added the link to the readme so it is easy to find for the next person. The link is: https://editor.drawthedots.com

Enjoy!
